"""add ical_url to property

Revision ID: 70661236c1c5
Revises: 91f6229a677b
Create Date: 2026-03-25 05:53:49.706560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70661236c1c5'
down_revision: Union[str, Sequence[str], None] = '91f6229a677b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('ical_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property', 'ical_url')
    # ### end Alembic commands ###
