"""add sync fields to property and rental

Revision ID: 75fbefada963
Revises: 70661236c1c5
Create Date: 2026-03-27 00:56:03.529709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75fbefada963'
down_revision: Union[str, Sequence[str], None] = '70661236c1c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('sync_token', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_property_sync_token'), 'property', ['sync_token'], unique=True)
    op.add_column('rentals', sa.Column('external_uid', sa.String(length=255), nullable=True))
    op.add_column('rentals', sa.Column('is_external', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_rentals_external_uid'), 'rentals', ['external_uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rentals_external_uid'), table_name='rentals')
    op.drop_column('rentals', 'is_external')
    op.drop_column('rentals', 'external_uid')
    op.drop_index(op.f('ix_property_sync_token'), table_name='property')
    op.drop_column('property', 'sync_token')
    # ### end Alembic commands ###
